version: "3"

services:
    locust:
        image: locustio/locust
        ports:
            - "8089:8089" # Web UI
        volumes:
            - ./locustfile.py:/mnt/locust/locustfile.py
        command: >
            -f /mnt/locust/locustfile.py
            --host=http://server.local
