apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS myapp;
    USE myapp;
    CREATE TABLE `User` (
        `id` INTEGER NOT NULL AUTO_INCREMENT,
        `email` VARCHAR(191) NOT NULL,
        `password` VARCHAR(191) NOT NULL,
        `name` VARCHAR(191) NULL,
        `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
        `updatedAt` DATETIME(3) NOT NULL,

        UNIQUE INDEX `User_email_key`(`email`),
        PRIMARY KEY (`id`)
    ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

---
apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-init
spec:
  template:
    spec:
      containers:
        - name: mysql-client
          image: percona:8.0
          command: ["sh", "-c"]
          args:
            - mysql -h cluster1-haproxy -uroot -prootpassword < /mnt/init/init.sql
          volumeMounts:
            - name: init-volume
              mountPath: /mnt/init
      restartPolicy: OnFailure
      volumes:
        - name: init-volume
          configMap:
            name: mysql-init-script
